### ISSUE TITLE
pydata_sphinx_theme 0.14.1 breaks current website look

### ISSUE THREAD

**Issue by melissawm** [matplotlib/mpl-sphinx-theme#80]
Building the docs with the newest PyData Sphinx Theme (0.14.1) creates a few inconsistent visual elements, most glaringly the top navbar (note also the accent color):

![Screenshot_20231005_171848](https://github.com/matplotlib/mpl-sphinx-theme/assets/3949932/598adae1-eaca-44be-929b-491369ca3794)

**Comment by ksunden** [comment]
The navbar positioning seems to be a function of width of window... wider and it looks perfectly fine, narrower and it gets collapsed into a hamburger menu, but there is the squishy middle where it still does the top bar but makes the right hand items two levels and line breaks the two word headings.

That much _does_ happen with e.g. 0.13.3 (what current docs are built with), but is made more prominent in 0.14 because the search bar is no longer just an icon.

I do agree that the accent color seems to have change, despite having what used to set it in the css:

https://github.com/matplotlib/mpl-sphinx-theme/blob/6d13c7b1c1ed722d63d08697cd48278a9615acc4/mpl_sphinx_theme/static/css/style.css#L32-L34

Also darkmode changed from a darker black/grey tone to a blue tone background color

**Comment by melissawm** [comment]
Sorry I should have mentioned that this happens on a maximized window so I think the issue is there anyway. There will surely be other problems with the new version though, maybe we should collect all of them here?

**Comment by jklymak** [comment]
Looks like they did this purposefully for accessibility reasons.  https://github.com/pydata/pydata-sphinx-theme/pull/1353. I'm not a fan aesthetically, but I don't know the accessibility arguments.  Looks like there are new knobs though: https://github.com/pydata/pydata-sphinx-theme/discussions/835. See also https://github.com/pydata/pydata-sphinx-theme/discussions/835

Probably should pin until someone has a chance to sift through and set the correct settings.

**Comment by melissawm** [comment]
The pin is there on `requirements/doc_requirements.txt` but not in `environment.yml` which is how I found this issue. Is there a plan for keeping those two files synchronized?

**Comment by jklymak** [comment]
Are you talking about in matplotlib/matplotlib?

**Comment by melissawm** [comment]
Yes, sorry 😄

**Comment by jklymak** [comment]
I don't actually see a pin there so not sure what is going on. Maybe pinned on CI?

**Comment by ksunden** [comment]
https://github.com/matplotlib/matplotlib/blob/a99673c970bc1dac1e54175ed3166e5190c9d793/requirements/doc/doc-requirements.txt#L17

Here is the pin that is used by CI (and builds for releases)

**Comment by timhoffm** [comment]
There is no out-of-the-box solution for syncing, but we could cobble up a script that does it reasonably well and run that on CI.

Theoretically, version bumps only happen with rarely and no sync was sort of good enough. But we needed quite a bit of pinning recently, so it might be worth to look into this.
